cvapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'cvapp'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^hire/$', views.hire, name='hire'),
    url(r'^about/$', views.about, name='about')
]
if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cvproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import cvapp
urlpatterns = [
    url(r'',include('cvapp.urls')),
    url(r'^admin/', admin.site.urls)
]

cvapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
# Create your models here.

cvapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import HttpResponse


# Create your views here.

def index(request):
    return render(request, "index.html", {'title': 'Home'})

def hire(request):
    return render(request, "hire.html", {'title': 'Home'})

def about(request):
	return render(request, 'blog/about.html', {'title': 'About'})

templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}

	<!-- start banner Area -->
	<section class="banner-area relative">
		<div class="container">
			<div class="row d-flex align-items-center justify-content-center">
				<div class="about-content col-lg-12">
					<h1 class="text-white">
						About Gustave
					</h1>
					<p class="link-nav">
						<span class="box">
							<a href="{% url 'cvapp:index' %}">Home </a>
							<a href="{% url 'cvapp:about' %}">About</a></p>
					</span>
				</div>
			</div>
		</div>
	</section>
	<!-- End banner Area -->
	<!-- Start Contact Area -->
	<section class="contact-area section-gap">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="contact-title">
						<h2>Contact Me</h2>
						<p>If you are looking at blank cassettes on the web, you may be very confused at the difference in price. You may see
							some for as low as $.17 each.</p>
					</div>
				</div>
			</div>

			<div class="row mt-80">
				<div class="col-lg-4 col-md-4">
					<div class="contact-box">
						<h4>+44 2365 654 8962</h4>
					</div>
				</div>
				<div class="col-lg-4 col-md-4">
					<div class="contact-box">
						<h4>information@colorlib.com</h4>
					</div>
				</div>
				<div class="col-lg-4 col-md-4">
					<div class="contact-box">
						<h4>kenedyjackson.me</h4>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-12 text-center">
					<a href="#" class="primary-btn mt-50" data-text="Hire Me">
						<span>H</span>
						<span>i</span>
						<span>r</span>
						<span>e</span>
						<span> </span>
						<span>M</span>
						<span>e</span>
					</a>
				</div>
			</div>
		</div>
	</section>
	<!-- End Contact Area -->
	
{% endblock content %}

templates/blog/base.html
<!DOCTYPE html>
<html lang="en">

<head>{% load static %}
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="shortcut icon" href="img/fav.png">
	<meta name="author" content="colorlib">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta charset="UTF-8">
    <title>Gustave Personal</title>
   	<!-- {% if title %}
	<title>Gustave Personal - {{ title }}</title>
	{% else %}
	<title>Gustave Personal</title>
	{% endif %}

			CSS
			============================================= -->
	<link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
	<link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body>

	<!-- Start Preloader Area -->
	<div class="preloader-area">
		<div class="loader-box">
			<div class="loader"></div>
		</div>
	</div>
	<!-- End Preloader Area -->


    
    <div class="container">
            <div class="row">
                <div class="col-sm-12">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ messages.tags }}">
                       {{ message }} 
                    </div>
                {% endfor %}
            {% endif %}
            {% block content %}

            {% endblock %}
                </div>
            </div>
        </div>


    <!-- start footer Area -->
	<footer class="footer-area">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-12">
                        <div class="footer-top flex-column">
                            <div class="footer-logo">
                                <a href="#">
                                    <img src="img/logo.png" alt="">
                                </a>
                                <h4>Follow Me</h4>
                            </div>
                            <div class="footer-social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row footer-bottom justify-content-center">
                    <p class="col-lg-8 col-sm-12 footer-text">
                        
    Copyright &copy;
    <script>
    document.write(new Date().getFullYear());
    </script>
    All rights reserved by <a href="mailto:muhozagustave1213@gmail.com" target="_blank">Gustave</a>
    </p>
                </div>
            </div>
        </footer>
        <!-- End footer Area -->
    
        <!-- ####################### Start Scroll to Top Area ####################### -->
        <div id="back-top">
            <a title="Go to Top" href="#">
                <i class="lnr lnr-arrow-up"></i>
            </a>
        </div>
        <!-- ####################### End Scroll to Top Area ####################### -->
    
        <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/easing.min.js' %}"></script>
        <script src="{% static 'js/hoverIntent.js' %}"></script>
        <script src="{% static 'js/superfish.min.js' %}"></script>
        <script src="{% static 'js/mn-accordion.js' %}"></script>
        <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
        <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
        <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'js/jquery.circlechart.js' %}"></script>
        <script src="{% static 'js/mail-script.js' %}"></script>
        <script src="{% static 'js/wow.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
    
    </body>
    
    </html>

templates/blog/hireNav.html
{% load static %}
	<!-- Start Header Area -->
	<header id="header">
		<div class="container main-menu">
			<div class="row align-items-center d-flex">
				<div id="logo">
					<a href="index.html"><img src="img/logo.png" alt="" title="" /></a>
				</div>
				<nav id="nav-menu-container">
					<ul class="nav-menu">
						<li class=""><a class="active" href="{% url 'cvapp:index' %}">Home</a></li>
						<li><a href="#about">About</a></li>
						<li class="menu-has-children"><a href="">Blog</a>
							<ul>
								<li><a href="blog-home.html">Blog Home</a></li>
								<li><a href="blog-single.html">Blog Single</a></li>
							</ul>
						</li>
					</ul>
				</nav>
			</div>
		</div>
	</header>
    <!-- End Header Area -->

templates/blog/nav1.html
{% load static %}
	<!-- Start Header Area -->
	<header id="header">
		<div class="container main-menu">
			<div class="row align-items-center d-flex">
				<div id="logo">
					<a href="index.html"><img src="img/logo.png" alt="" title="" /></a>
				</div>
				<nav id="nav-menu-container">
					<ul class="nav-menu">
						<li class=""><a class="active" href="{% url 'cvapp:index' %}">Home</a></li>
						<li><a href="#about">About</a></li>
						<li><a href="#work">Recent Work</a></li>
						<li class="menu-has-children"><a href="#">More</a>
							<ul>
								<li><a href="#service">Services</a></li>
								<li><a href="#contact">Contact</a></li>
								<li><a href="#jobhistory">Job History</a></li>
							</ul>
						</li>
						<li class="menu-has-children"><a href="">Blog</a>
							<ul>
								<li><a href="blog-home.html">Blog Home</a></li>
								<li><a href="blog-single.html">Blog Single</a></li>
							</ul>
						</li>
					</ul>
				</nav>
			</div>
		</div>
	</header>
    <!-- End Header Area -->

templates/hire.html
{% extends "blog/base.html" %}
    {% block content %}

    {% include 'blog/hireNav.html' %}
	<!-- start banner Area -->
	<section class="banner-area relative">
		<div class="container">
			<div class="row d-flex align-items-center justify-content-center">
				<div class="about-content col-lg-12">
					<h1 class="text-white">
						Hire Me
					</h1>
					<p class="link-nav">
						<span class="box">
							<a href="{% url 'cvapp:index' %}">Home </a>
							<a href="{% url 'cvapp:hire' %}">Contact</a>
						</span>
					</p>
				</div>
			</div>
		</div>
	</section>
	<!-- End banner Area -->

	<!-- Start contact-page Area -->
	<section class="contact-page-area section-gap-top">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 d-flex flex-column address-wrap">
					<div class="single-contact-address d-flex flex-row">
						<div class="icon">
							<span class="lnr lnr-home"></span>
						</div>
						<div class="contact-details">
							<h5>Kigali, Rwanda</h5>
							<p>
								kk 32 st
							</p>
						</div>
					</div>
					<div class="single-contact-address d-flex flex-row">
						<div class="icon">
							<span class="lnr lnr-phone-handset"></span>
						</div>
						<div class="contact-details">
							<h5>+2507 8784 8876</h5>
							<p>All time available</p>
						</div>
					</div>
					<div class="single-contact-address d-flex flex-row">
						<div class="icon">
							<span class="lnr lnr-envelope"></span>
						</div>
						<div class="contact-details">
							<h5>muhozagustave1213@gmail.com</h5>
							<p>Send your query anytime!</p>
						</div>
					</div>
				</div>
				<div class="col-lg-8">
					<form class="form-area " id="myForm" action="mail.php" method="post" class="contact-form text-right">
						<div class="row">
							<div class="col-lg-6 form-group form-group-top">
								<input name="org_name" placeholder="Organization Name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Organization Name'"
								 class="common-input mb-20 form-control" required="" type="text">

								<input name="position" placeholder="Available Position" onfocus="this.placeholder = ''"
								 onblur="this.placeholder = 'Available Position'" class="common-input mb-20 form-control" required="" type="text">

								<input name="requirements" placeholder="Major skills required" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Major skills required'"
								 class="common-input mb-20 form-control" required="" type="text">
							</div>
							<div class="col-lg-6 form-group">
								<textarea class="common-textarea form-control" name="message" placeholder="Some addition details" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Some addition details'"></textarea>
							</div>
							<div class="col-lg-12">
								<div class="alert-msg" style="text-align: left;"></div>

								<button class="primary-btn" style="float: right;" data-text="Send">
									<span>S</span>
									<span>e</span>
									<span>n</span>
									<span>d</span>
									<span> </span>
									<span>M</span>
									<span>e</span>
									<span>s</span>
									<span>s</span>
									<span>a</span>
									<span>g</span>
									<span>e</span>

								</button>
							</div>
						</div>
					</form>
				</div>

				<div class="col-lg-12">
					<div class="map-wrap" style="width:100%; height: 445px;" id="map"></div>
				</div>
			</div>
		</div>
	</section>
	<!-- End contact-page Area -->
	{% endblock content %}

templates/index.html
{% extends "blog/base.html" %}
{% block content %}


{% include 'blog/nav1.html' %}
	<!-- start banner Area -->
	<section class="home-banner-area">
		<div class="container">
			<div class="row fullscreen d-flex align-items-center">
				<div class="banner-content col-lg-6 col-md-12 justify-content-center ">
					<div class="me wow fadeInDown" data-wow-duration="1s" data-wow-delay="1.2s">It's me</div>
					<h1 class="wow fadeInUp" data-wow-duration="1s" data-wow-delay="1.7s">Gustave MUHOZA</h1>
					<div class="designation mb-50 wow fadeInUp" data-wow-duration="1s" data-wow-delay="2.1s">
						Senior Web
						<span class="designer">Designer</span>
						and Content
						<span class="developer">Developer</span>
					</div>
					<a href="{% url 'cvapp:hire' %}" class="primary-btn" data-text="Hire Me">
						<span>H</span>
						<span>i</span>
						<span>r</span>
						<span>e</span>
						<span> </span>
						<span>M</span>
						<span>e</span>
					</a>
				</div>
				<div class="banner-img col-lg-6 col-md-6 align-self-end">
					
				</div>
			</div>
		</div>
	</section>
	<!-- End banner Area -->


	<!-- Start About Area -->
	<section class="about-area section-gap" id="about">
		<div class="container">
			<div class="row align-items-center justify-content-between">
				<div class="col-lg-6 about-left">
						<div class="section-title">
								<h2>about myself</h2>
							</div>
							<p>
									I am an allround web developer. I am senior programmerwith good knowledge of front-end techniques.
									I love structure and order and i also stand for quality. I love spending time on fixing little details optimizing web apps.
									Also i like working in team and learn faster and much more.
								</p>
								<p>That’s why it’s crucial that, as Developer, our behavior on the job is beyond reproach. inappropriate behavior is often
									laughed.
								</p>
					<a href="{% url 'cvapp:hire' %}" class="primary-btn white" data-text="More Info">
							<span>M</span>
							<span>o</span>
							<span>r</span>
							<span>e</span>
							<span> </span>
							<span>I</span>
							<span>n</span>
							<span>f</span>
							<span>o</span>
						</a>
				</div>
				<div class="col-lg-5 col-md-12 about-right">
						<div class="section-title">
								<h2>Who am i?</h2>
							</div>
					<div class="mb-50 wow fadeIn" data-wow-duration=".8s">
						<p>
							I'm creative Python and Nodejs webdeveloper
							<hr class="bottom_line">
							<img src="{{ STATIC_URL }}img/Gustavepic.jpg" alt="">
							<img src="{% static 'img/Gustavepic.jpg' %}" alt="" class="img-thumbnail img-circle" />
						</p>
					</div>
					<a href="#" class="primary-btn" data-text="Resume">
						<span>R</span>
						<span>e</span>
						<span>s</span>
						<span>u</span>
						<span>m</span>
						<span>e</span>
					</a>
				</div>
			</div>
		</div>
	</section>
	<!-- End About Area -->


	<!-- Start Work Area Area -->
	<section class="work-area section-gap-top section-gap-bottom-90" id="work">
		<div class="container">
			<div class="row d-flex justify-content-between align-items-end mb-80">
				<div class="col-lg-6">
					<div class="section-title">
						<h2>Latest Works</h2>
						<p>If you are looking at blank cassettes on the web, you may be very confused at the difference in price. You may see
							some for as low as $.17 each.</p>
					</div>
				</div>

				<div class="col-lg-6">
					<div class="filters">
						<ul>
							<li class="active" data-filter=".all">All Categories</li>
							<li data-filter=".branding">Branding</li>
							<li data-filter=".creative">Creative Work</li>
							<li data-filter=".web-design">Web Design</li>
						</ul>
					</div>
				</div>
			</div>

			<div class="filters-content">
				<div class="row grid">
					<div class="single-work col-lg-4 col-md-6 col-sm-12 all creative wow fadeInUp" data-wow-duration="2s">
						<div class="relative">
							<div class="thumb">
								<div class="overlay overlay-bg"></div>
								<img class="image img-fluid" src="img/work/w1.jpg" alt="">
							</div>
							<div class="middle">
								<h4>2D Vinyl Design</h4>
								<div class="cat">Client Project</div>
							</div>
							<a class="overlay" href="portfolio-details.html"></a>
						</div>
					</div>
					<div class="single-work col-lg-4 col-md-6 col-sm-12 all web-design branding wow fadeInUp" data-wow-duration="2s" data-wow-delay="0.2s">
						<div class="relative">
							<div class="thumb">
								<div class="overlay overlay-bg"></div>
								<img class="image img-fluid" src="img/work/w2.jpg" alt="">
							</div>
							<div class="middle">
								<h4>2D Vinyl Design</h4>
								<div class="cat">Client Project</div>
							</div>
							<a class="overlay" href="portfolio-details.html"></a>
						</div>
					</div>
					<div class="single-work col-lg-4 col-md-6 col-sm-12 all branding web-design wow fadeInUp" data-wow-duration="2s" data-wow-delay="0.4s">
						<div class="relative">
							<div class="thumb">
								<div class="overlay overlay-bg"></div>
								<img class="image img-fluid" src="img/work/w3.jpg" alt="">
							</div>
							<div class="middle">
								<h4>2D Vinyl Design</h4>
								<div class="cat">Client Project</div>
							</div>
							<a class="overlay" href="portfolio-details.html"></a>
						</div>
					</div>
					<div class="single-work col-lg-4 col-md-6 col-sm-12 all web-design wow fadeInUp" data-wow-duration="2s" data-wow-delay="0.6s">
						<div class="relative">
							<div class="thumb">
								<div class="overlay overlay-bg"></div>
								<img class="image img-fluid" src="img/work/w6.jpg" alt="">
							</div>
							<div class="middle">
								<h4>2D Vinyl Design</h4>
								<div class="cat">Client Project</div>
							</div>
							<a class="overlay" href="portfolio-details.html"></a>
						</div>
					</div>
					<div class="single-work col-lg-4 col-md-6 col-sm-12 all creative wow fadeInUp" data-wow-duration="2s">
						<div class="relative">
							<div class="thumb">
								<div class="overlay overlay-bg"></div>
								<img class="image img-fluid" src="img/work/w4.jpg" alt="">
							</div>
							<div class="middle">
								<h4>2D Vinyl Design</h4>
								<div class="cat">Client Project</div>
							</div>
							<a class="overlay" href="portfolio-details.html"></a>
						</div>
					</div>
					<div class="single-work col-lg-4 col-md-6 col-sm-12 all branding wow fadeInUp" data-wow-duration="2s" data-wow-delay="0.2s">
						<div class="relative">
							<div class="thumb">
								<div class="overlay overlay-bg"></div>
								<img class="image img-fluid" src="img/work/w5.jpg" alt="">
							</div>
							<div class="middle">
								<h4>2D Vinyl Design</h4>
								<div class="cat">Client Project</div>
							</div>
							<a class="overlay" href="portfolio-details.html"></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Work Area Area -->


	<!-- Start Job History Area Area -->
	<section class="job-area section-gap-top section-gap-bottom-90" id="jobhistory">
		<div class="container">
			<div class="row d-flex">
				<div class="col-lg-12">
					<div class="section-title">
						<h2>Job History</h2>
						<p>Still in college doing BIT</p><br>
							<p>
								I am about to graduate college at the end of 2019.
								Soon my job will be posted
							</p>
					</div>
				</div>
			</div>

			<div class="row">
				<div>
					<h3>Sorry, No Job History Yet</h3>
				</div>
			</div>
		</div>
	</section>
	<!-- End Job Historyt Area Area -->


	<!-- Start Service Area -->
	<section class="service-area section-gap" id="service">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="section-title">
						<h2>Service Offers</h2>
						<p>If you are looking for someone to help you on the web you have, Don't be confused at the difference in price or anything. You may see
							some solutions from my knowledge.</p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-3 col-md-6">
					<div class="single-service wow fadeInUp" data-wow-duration="1s">
						<span class="lnr lnr-screen"></span>
						<h4>
							<span>Web</span> Design
						</h4>
						<p>If you’re looking blank casvsettes on the web, you may confuse.</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="single-service wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.2s">
						<span class="lnr lnr-laptop-phone"></span>
						<h4><span>Application</span> Development
						</h4>
						<p>If you’re looking blank casvsettes on the web, you may confuse.</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="single-service wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.4s">
						<span class="lnr lnr-database"></span>
						<h4><span>Web</span> Development
						</h4>
						<p>If you’re looking blank casvsettes on the web, you may confuse.</p>
					</div>
				</div>
				<div class="col-lg-3 col-md-6">
					<div class="single-service wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.6s">
						<span class="lnr lnr-chart-bars"></span>
						<h4><span>Web</span> Development
						</h4>
						<p>If you’re looking blank casvsettes on the web, you may confuse.</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Service Area -->


	<!-- Start Testimonials Area -->
	<section class="testimonials_area section-gap">
		<div class="container">
			<div class="testi_slider owl-carousel">
				<div class="item">
					<div class="testi_item">
						<img src="img/quote.png" alt="">
						<h4>Fanny Spencer</h4>
						<ul class="list">
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
						</ul>
						<div class="wow fadeIn" data-wow-duration="1s">
							<p>
								As conscious traveling Paup ers we must always be oncerned about our dear Mother Earth. If you think about it, you travel
								across her face <br> and She is the host to your journey.
							</p>
						</div>
					</div>
				</div>
				<div class="item">
					<div class="testi_item">
						<img src="img/quote.png" alt="">
						<h4>Fanny Spencer</h4>
						<ul class="list">
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
						</ul>
						<div class="wow fadeIn" data-wow-duration="1s">
							<p>
								As conscious traveling Paup ers we must always be oncerned about our dear Mother Earth. If you think about it, you travel
								across her face <br> and She is the host to your journey.
							</p>
						</div>
					</div>
				</div>
				<div class="item">
					<div class="testi_item">
						<img src="img/quote.png" alt="">
						<h4>Fanny Spencer</h4>
						<ul class="list">
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
							<li><a href="#"><i class="fa fa-star"></i></a></li>
						</ul>
						<div class="wow fadeIn" data-wow-duration="1s">
							<p>
								As conscious traveling Paup ers we must always be oncerned about our dear Mother Earth. If you think about it, you travel
								across her face <br> and She is the host to your journey.
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- End Testimonials Area -->


	<!-- Start Contact Area -->
	<section class="contact-area section-gap" id="contact">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="contact-title">
						<h2>Contact Me</h2>
						<p>If you are looking for someone to help you on the web you have, Don't be confused at the difference in price or anything. You may see
							some solutions from my knowledge.</p>
					</div>
				</div>
			</div>

			<div class="row mt-80">
				<div class="col-lg-4 col-md-4">
					<div class="contact-box">
						<h4>+25 0787 848 876</h4>
					</div>
				</div>
				<div class="col-lg-4 col-md-4">
					<div class="contact-box">
						<h4>muhozagustave1213@gmail.com</h4>
					</div>
				</div>
				<div class="col-lg-4 col-md-4">
					<div class="contact-box">
						<h4>GustaveMuhoza.io</h4>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-12 text-center">
					<a href="{% url 'cvapp:hire' %}" class="primary-btn mt-50" data-text="Hire Me">
						<span>H</span>
						<span>i</span>
						<span>r</span>
						<span>e</span>
						<span> </span>
						<span>M</span>
						<span>e</span>
					</a>
				</div>
			</div>
		</div>
	</section>
	<!-- End Contact Area -->


	{% endblock content %}